version: "3.8"

services:
  frontend:
    build:
      context: ./client
    ports:
      - "3000:80"
    depends_on:
      - backend 
  backend:
    build:
      context: ./server 
    ports:
      - "6969:6969"